"""empty message

Revision ID: 12062da389ba
Revises: e3355d3ec45b
Create Date: 2020-06-05 15:00:08.343929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12062da389ba'
down_revision = 'e3355d3ec45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255)))
    op.execute('UPDATE users SET password=email')
    op.alter_column('users', 'password', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
